package com.netlight.quotes.app.model.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.netlight.quotes.app.model.db.Quote;

import com.netlight.quotes.app.model.dao.QuoteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig quoteDaoConfig;

    private final QuoteDao quoteDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        quoteDaoConfig = daoConfigMap.get(QuoteDao.class).clone();
        quoteDaoConfig.initIdentityScope(type);

        quoteDao = new QuoteDao(quoteDaoConfig, this);

        registerDao(Quote.class, quoteDao);
    }
    
    public void clear() {
        quoteDaoConfig.getIdentityScope().clear();
    }

    public QuoteDao getQuoteDao() {
        return quoteDao;
    }

}
