package com.netlight.quotes.app.model.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.netlight.quotes.app.model.db.Quote;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table QUOTE.
*/
public class QuoteDao extends AbstractDao<Quote, Long> {

    public static final String TABLENAME = "QUOTE";

    /**
     * Properties of entity Quote.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Quote = new Property(1, String.class, "quote", false, "QUOTE");
        public final static Property Author = new Property(2, String.class, "author", false, "AUTHOR");
        public final static Property Category = new Property(3, String.class, "category", false, "CATEGORY");
    };


    public QuoteDao(DaoConfig config) {
        super(config);
    }
    
    public QuoteDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'QUOTE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'QUOTE' TEXT NOT NULL ," + // 1: quote
                "'AUTHOR' TEXT NOT NULL ," + // 2: author
                "'CATEGORY' TEXT NOT NULL );"); // 3: category
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'QUOTE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Quote entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getQuote());
        stmt.bindString(3, entity.getAuthor());
        stmt.bindString(4, entity.getCategory());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Quote readEntity(Cursor cursor, int offset) {
        Quote entity = new Quote( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // quote
            cursor.getString(offset + 2), // author
            cursor.getString(offset + 3) // category
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Quote entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setQuote(cursor.getString(offset + 1));
        entity.setAuthor(cursor.getString(offset + 2));
        entity.setCategory(cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Quote entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Quote entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
