package com.netlight.quotes.app.model.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import android.os.Parcel;
import android.os.Parcelable;

import com.netlight.quotes.app.model.dto.QuoteDto;
// KEEP INCLUDES END
/**
 * Entity mapped to table "QUOTE".
 */
public class Quote implements Parcelable {

    private Long id;
    /** Not-null value. */
    private String quote;
    /** Not-null value. */
    private String author;
    /** Not-null value. */
    private String category;
    private boolean yodafied;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Quote() {
    }

    public Quote(Long id) {
        this.id = id;
    }

    public Quote(Long id, String quote, String author, String category, boolean yodafied) {
        this.id = id;
        this.quote = quote;
        this.author = author;
        this.category = category;
        this.yodafied = yodafied;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getQuote() {
        return quote;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setQuote(String quote) {
        this.quote = quote;
    }

    /** Not-null value. */
    public String getAuthor() {
        return author;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAuthor(String author) {
        this.author = author;
    }

    /** Not-null value. */
    public String getCategory() {
        return category;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategory(String category) {
        this.category = category;
    }

    public boolean getYodafied() {
        return yodafied;
    }

    public void setYodafied(boolean yodafied) {
        this.yodafied = yodafied;
    }

    // KEEP METHODS - put your custom methods here

    public Quote(QuoteDto quoteDto, boolean yodafied) {
        quote = quoteDto.getQuote();
        author = quoteDto.getAuthor();
        category = quoteDto.getCategory();
        this.yodafied = yodafied;
    }


    protected Quote(Parcel in) {
        quote = in.readString();
        author = in.readString();
        category = in.readString();
    }

    public static final Creator<Quote> CREATOR = new Creator<Quote>() {
        @Override
        public Quote createFromParcel(Parcel in) {
            return new Quote(in);
        }

        @Override
        public Quote[] newArray(int size) {
            return new Quote[size];
        }
    };

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(quote);
        dest.writeString(author);
        dest.writeString(category);
    }
    // KEEP METHODS END

}
